### PR TITLE
Correctd all typos I found

### PR DESCRIPTION
**Pull request by CSteigueber**
Sorry, I just saw the rule about just fixing 5 typos after I was done

### CODE REVIEW

**Comment by sanderdms** [comment]
Thanks. Maybe you can add couple paragraphs from the original article. To leave some errors for others to correct. https://github.com/sanderdms/spelling-correction/issues/

I can merge after this issue is resolved...

**Comment by CSteigueber** [comment]
Done, only first two paragraphs are corrected, now.

**Comment by CSteigueber** [comment]
Woops, actually thought you meant the you posted with original. Will look into it.

**Comment by sanderdms** [comment]
Awesome. Also remember to make a separate branch for making changes / adding features
I believe that's a best practice.

> Woops, actually thought you meant the one you posted with original. Will look into it.

Awesome. Also remember to make a separate branch for making changes / adding features
I believe that's a best practice.

**Comment by CSteigueber** [comment]
I can't access the original article (without typos) because my reading limit for medium is already reached. Can you plaese put the original file into the repository as well?

**Comment by sanderdms** [comment]
I've added to original to the repo.
https://github.com/sanderdms/spelling-correction/blob/master/original.md

PS: you can post the article to twitter and click to the article via Twitter generated link. (Medium unlocks all articles shared from Twitter) Or if you are hack savy you can inject the twitter referrer into the request headers :black_flag: I use this chrome extension to modify request headers:https://chrome.google.com/webstore/detail/modheader/idgpnmonknjnojddfkpgkljpfnnfcklj?hl=en

**Comment by CSteigueber** [comment]
I started a new pull request with another branch that includes the file with more paragraphs.
I suggest we close this pull request here and look at the other one.

**Pull request closed without merging**
